books/urls.py
from django.urls import path, include
from .views import Search
# from .views import registerBook
from .views import book_info, reading_books, read_books, readed_books, myBooks, statusBook

app_name = 'books'

urlpatterns = [
	path('search/', Search, name='search'),
	path('book_info/<int:pk>', book_info, name='book_info'),
    path('ler/', read_books, name='read_books'),
    path('lendo/', reading_books, name='reading_books'),
    path('lido/', readed_books, name='readed_books'),
    path('myBooks/', myBooks, name='myBooks'),
    path('statusBook/<int:pk>/<slug:status>', statusBook, name='statusBook'),
]

skoob/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import TemplateView

from django.conf import settings
from django.conf.urls.static import static
from books.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', TemplateView.as_view(template_name='home.html'), name='home'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('users/', include('users.urls', namespace='users')),
    path('', home, name='home'),
    path('books/', include('books.urls', namespace='books')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path, include
from .views import registerUser, profile

app_name = 'users'
urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('register/', registerUser, name='registerUser'),
    path('profile/', profile, name='profile'),
]

books/models.py
from django.contrib.auth.models import User
from django.db import models


class Livro(models.Model):

    capa = models.ImageField(
        'Imagem da capa',
        upload_to='imagens/livros/',
        default='imagens/none/no-img.jpg'
    )

    titulo = models.CharField(
        'Nome',
        max_length=40
    )

    genero = models.CharField(
        'Genero',
        max_length=100
    )

    autor = models.CharField(
        'Autor',
        max_length=50
    )

    editora = models.CharField(
        'Editora',
        max_length=50
    )

    sinopse = models.TextField(
        'Sinopse',
        max_length=700,
        default='Sem Sinopse'
    )

    paginas = models.IntegerField(
        'Número de páginas'
    )

    def __str__(self):
        return self.titulo

    class Meta:
        verbose_name = 'livro'
        verbose_name_plural = 'livros'


class UserBook(models.Model):
    LER = 'LER'
    LENDO = 'LENDO'
    LIDO = 'LIDO'
    STATUS_BOOK = (
        (LER, 'Ler'),
        (LENDO, 'Lendo'),
        (LIDO, 'Lido'),
    )

    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='usersbooks'
    )

    livro = models.ForeignKey(
        Livro,
        on_delete=models.CASCADE,
        related_name='livros'
    )

    status = models.CharField(
        max_length=15,
        choices=STATUS_BOOK,
        default=LER
    )

    def __str__(self):
        return self.livro.titulo

    class Meta:
        verbose_name = 'userbook'
        verbose_name_plural = 'usersbooks'

users/models.py
from django.contrib.auth.models import User
from django.db import models


class Profile(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        related_name='profiles'
    )

    name = models.CharField(
        max_length=254
    )

    gender = models.CharField(
        max_length=10
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'profile'
        verbose_name_plural = 'profiles'

users/forms.py
from django import forms
from .models import Profile

class RegisterUser(forms.ModelForm):

    email = forms.EmailField()

    username = forms.CharField()

    password = forms.CharField()

    class Meta:
        model = Profile
        fields = ('name', 'gender')

books/views.py
from django.shortcuts import redirect, render
import operator
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from .models import Livro, UserBook


def Search(request):
    try:
        query = request.POST['search']
        result1 = 'Sua busca:';
        result2 = ', retornou os seguintes resultados.';
        result3 = 'Esse livro não está cadastrado.';

        livros = Livro.objects.filter(titulo__contains=query)
        if livros.exists():
            return render(request, 'results.html', {'livros':livros, 'query':query, 'result1':result1, 'result2':result2})
        else:
            return render(request, 'results.html', {'query':query, 'result1':result1, 'result2':result2, 'result3':result3})
    except KeyError:
        return render(request, 'home.html')

@login_required(login_url='/accounts/login/')
def statusBook(request, pk, status):
    try:
        book = UserBook.objects.get(user=request.user, livro=pk)
        book.status = status
        book.save()
    except UserBook.DoesNotExist:
        li = Livro.objects.get(pk=pk)
        book = UserBook(user=request.user, livro=li, status=status)
        book.save()
    userbook = UserBook.objects.get(user=request.user, livro=pk)
    books = Livro.objects.get(pk=pk)
    return render(request, 'books/book.html', {'books': books, 'userbook':userbook})

def home(request):
    books = Livro.objects.all()
    return render(request, 'home.html', {'books': books})

def book_info(request, pk):
    books = Livro.objects.get(pk=pk)
    ###Removi user=request.user do filtro
    userbook = UserBook.objects.filter(livro=pk)
    return render(request, 'books/book.html', {'books': books, 'userbook':userbook})

@login_required(login_url='/accounts/login/')
def myBooks(request):
    books = UserBook.objects.filter(user=request.user)
    return render(request, 'books/myBooks.html', {'books': books})


@login_required(login_url='/accounts/login/')
def reading_books(request):
    books = UserBook.objects.filter(user=request.user, status=UserBook.LENDO)
    return render(request, 'books/books-lendo.html', {'books': books})


@login_required(login_url='/accounts/login/')
def readed_books(request):
    books = UserBook.objects.filter(user=request.user, status=UserBook.LIDO)
    return render(request, 'books/books-lidos.html', {'books': books})


@login_required(login_url='/accounts/login/')
def read_books(request):
    books = UserBook.objects.filter(user=request.user, status=UserBook.LER)
    return render(request, 'books/books-ler.html', {'books': books})

users/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import redirect, render

from .forms import RegisterUser
from .models import Profile


def registerUser(request):
    if request.method == 'POST':
        form = RegisterUser(request.POST)
        if form.is_valid():
            user = User.objects.create_user(
                username=form['username'].value(),
                email=form['email'].value(),
                password=form['password'].value())
            profile = form.save(commit=False)
            profile.user = user
            profile.save()
            return redirect('users:login')
    else:
        form = RegisterUser()
        print(form.errors)
    return render(request, 'registration/cadastro.html', {'form': form})


@login_required
def profile(request):
    profiles = Profile.objects.filter(user=request.user)
    return render(request, 'registration/profile.html', {'profiles': profiles})

views.py
from django.shortcuts import render_to_response
from django.http import Http404, HttpResponse, HttpResponseRedirect

def search(request):

    if request.POST:
	print request.POST['term']
	return HttpResponseRedirect("/")
    else:
	return render_to_response('home.html')

templates/books/book.html
{% load staticfiles %}
{% load static %}

<!DOCTYPE html>
<html>
	<head>
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.1/css/bulma.min.css">
		<link rel="stylesheet" href="{% static 'css/bulma-carousel.min.css' %}">
		<link rel="stylesheet" href="{% static 'css/style.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'css/livro.css' %}">
    	<script defer src="https://use.fontawesome.com/releases/v5.1.0/js/all.js"></script>	
	</head>
	<body>
		<header class="navbar is-transparent">
			<div class="container">
				<div class="navbar-brand">
			        <a class="navbar-item" href="{% url 'home' %}">
			            <img src="{% static 'imagens/logo.png' %}" alt="Skoob">
			        </a>
				</div>
				<div id="navbar" class="navbar-menu">
			        <div class="navbar-end has-text-centered-mobile">
			            <div class="navbar-item">
			              <form method="post" class="search">
			              	<div class="field has-addons">
			              	  <div class="control">
			              	    <input class="input is-small" type="text" placeholder="Search.." name="search">
			              	  </div>
			              	  <div class="control">
			              	    <button class="button is-small" type="submit"><i class="fa fa-search"></i></button>
			              	  </div>
			              	</div>
			              </form>
			            </div>
			            <a class="navbar-item active-link" href="{% url 'home' %}">
			              Home
			            </a>
	                    {% if user.is_authenticated%}
			            <div class="navbar-item has-dropdown is-hoverable">
			                <a class="navbar-link active-link" href="{% url 'home' %}">
			                  Explore
			                </a>
			                <div class="navbar-dropdown is-boxed">
			                  <a class="navbar-item" href="{% url 'books:myBooks' %}">
			                    Estante
			                  </a>
			                  <a class="navbar-item" href="{% url 'books:reading_books' %}">
			                    Lendo
			                  </a>
			                  <a class="navbar-item" href="{% url 'books:readed_books' %}">
			                    Lidos
			                  </a>
	                          <a class="navbar-item" href="{% url 'books:read_books' %}">
	                            Ler
	                          </a>
	                          <a class="navbar-item" href="{% url 'users:profile' %}">
                                Perfil
                              </a>
			                </div>
	                    {% endif %}
			            </div>
			            <div class="navbar-item">
			            	{% block conten %}
			            	{% if user.is_authenticated %}
			            	  <a class="active-link" href="{% url 'logout' %}">Sair</a>
			            	{% else %}
			            	  <a class="button is-info is-outlined" href="{% url 'login' %}">Entrar</a>
			            	{% endif %}
			            	{% endblock %}
			            </div>
			        </div>
				</div>
			</div>
		</header>
		<section class="hero">
		{% block content %}
			<div class="hero-body">
			<div class="container conteudo">
				<div class="columns">
					<div class="column is-narrow">
					    <!--<div class="img"> removido para nao distorcer a imagem de capa do livro-->
                        <div>
							<img width="200" height="100" src="{{books.capa.url}}">
					    </div>
					</div>
			    	<div class="column">
			    		<div class="title is-3">{{books.titulo}}</div>
	    				
	    				    <div class="dados">
	    				    	{% block v_status %}
    				    		{% if userbook.status == 'LER' %}
    				    			<a class="button is-link is-hovered" href="{% url 'books:statusBook' pk=books.pk status='LER' %}">Ler</a>
    				    			<a class="button is-light" href="{% url 'books:statusBook' pk=books.pk status='LENDO' %}">Lendo</a>
    				    			<a class="button is-light" href="{% url 'books:statusBook' pk=books.pk status='LIDO' %}">Lido</a>
    				    		{% elif userbook.status == 'LENDO' %}
									<a class="button is-light" href="{% url 'books:statusBook' pk=books.pk status='LER' %}">Ler</a>
    				    			<a class="button is-primary is-hovered" href="{% url 'books:statusBook' pk=books.pk status='LENDO' %}">Lendo</a>
    				    			<a class="button is-light" href="{% url 'books:statusBook' pk=books.pk status='LIDO' %}">Lido</a>
    				    		{% elif userbook.status == 'LIDO' %}
    				    			<a class="button is-light" href="{% url 'books:statusBook' pk=books.pk status='LER' %}">Ler</a>
    				    			<a class="button is-light" href="{% url 'books:statusBook' pk=books.pk status='LENDO' %}">Lendo</a>
    				    			<a class="button is-success is-hovered" href="{% url 'books:statusBook' pk=books.pk status='LIDO' %}">Lido</a>
    				    		{% else %}
	  								<a class="button is-light" href="{% url 'books:statusBook' pk=books.pk status='LER' %}">Ler</a>
    				    			<a class="button is-light" href="{% url 'books:statusBook' pk=books.pk status='LENDO' %}">Lendo</a>
    				    			<a class="button is-light" href="{% url 'books:statusBook' pk=books.pk status='LIDO' %}">Lido</a>
	    				    	{% endif %}
	    				    	{% endblock %}
	    				    	 	

	    		        <table class="dadosLivro">
	    		            <tr>
	    		                <td>Autor:</td>
	    		                <td class="dados2">{{books.autor}}</td>
	    		            </tr>
	    		            <tr>
	    		                <td>Editora:</td>
	    		                <td class="dados2">{{books.editora}}</td>
	    		            </tr>
	    		            <tr>
	    		                <td>Gênero:</td>
	    		                <td class="dados2">{{books.genero}}</td>
	    		            </tr>
	    		            <tr>
	    		                <td>Nº de páginas:</td>
	    		                <td class="dados2">{{books.paginas}}</td>
	    		            </tr>
	    		        </table>
	    		        <div>
	    		        	<h5 class="title is-5">Sinopse</h5>
	    		        	<p>{{books.sinopse}}</p>
	    		        </div>
			    	</div>
			    </div>
			    </div>
		    </div>
		    {% endblock %}
		</div>
	</section>
	{% include "footer.html" %}
</body>
</html>

templates/books/books-lendo.html
{% include "header.html" %}

{% if user.is_authenticated %}
<div class="tabs is-centered">
	<ul>
		<li><a href="{% url 'books:myBooks' %}">Estante</a></li>
		<li><a href="{% url 'books:readed_books' %}">Lidos</a></li>
		<li><a href="{% url 'books:read_books' %}">Ler</a></li>
		<li class="is-active"><a href="{% url 'books:reading_books' %}">Lendo</a></li>
	</ul>
</div>
{% endif %}

<section class="livros">
	{% for book in books %}
		<div class=" box-livro">
		  <a class="image" href="{% url 'books:book_info' pk=book.livro.pk %}" title="{{book.livro.titulo}}">
		    <img src="{{book.livro.capa.url}}"" >  
		    <p class="has-text-weight-semibold">{{book.livro.titulo}}</p>
		  </a>
		</div>
	{% endfor %}
</section>

</div>
</div>
</section>
</section>
{% include "footer.html" %}
	</body>
</html>

templates/books/books-ler.html
{% include "header.html" %}
{% if user.is_authenticated %}
<div class="tabs is-centered">
  <ul>
    <li><a href="{% url 'books:myBooks' %}">Estante</a></li>
    <li><a href="{% url 'books:readed_books' %}">Lidos</a></li>
    <li class="is-active"><a href="{% url 'books:read_books' %}">Ler</a></li>
    <li><a href="{% url 'books:reading_books' %}">Lendo</a></li>
  </ul>
</div>
{% endif %}

	<section class="livros">
		{% for book in books %}
        <div class=" box-livro">
          <a class="image" href="{% url 'books:book_info' pk=book.livro.pk %}" title="{{book.livro.titulo}}">
            <img src="{{book.livro.capa.url}}"" >  
            <p class="has-text-weight-semibold">{{book.livro.titulo}}</p>
          </a>
        </div>
		{% endfor %}
	</section>

</div>
</div>
</section>
</section>
{% include "footer.html" %}

  </body>
</html>

templates/books/books-lidos.html
{% include "header.html" %}

{% if user.is_authenticated %}
<div class="tabs is-centered">
	<ul>
		<li><a href="{% url 'books:myBooks' %}">Estante</a></li>
		<li class="is-active"><a href="{% url 'books:readed_books' %}">Lidos</a></li>
		<li><a href="{% url 'books:read_books' %}">Ler</a></li>
		<li><a href="{% url 'books:reading_books' %}">Lendo</a></li>
	</ul>
</div>
{% endif %}

<section class="livros">
	{% for book in books %}
        <div class=" box-livro">
		  <a class="image" href="{% url 'books:book_info' pk=book.livro.pk %}" title="{{book.livro.titulo}}">
		    <img src="{{book.livro.capa.url}}"" >  
		    <p class="has-text-weight-semibold">{{book.livro.titulo}}</p>
		  </a>
		</div>
	{% endfor %}
</section>

</div>
</div>
</section>
</section>
{% include "footer.html" %}
	</body>
</html>

templates/books/myBooks.html
{% include "header.html" %}
{% if user.is_authenticated %}
<div class="tabs is-centered">
  <ul>
    <li class="is-active"><a href="{% url 'home' %}">Estante</a></li>
    <li><a href="{% url 'books:readed_books' %}">Lidos</a></li>
    <li><a href="{% url 'books:read_books' %}">Ler</a></li>
    <li><a href="{% url 'books:reading_books' %}">Lendo</a></li>
  </ul>
</div>
{% endif %}

    <section class="livros">

        {% for book in books %}
            <div class=" box-livro">
              <a class="image" href="{% url 'books:book_info' pk=book.livro.pk %}" title="{{book.livro.titulo}}">
                <img src="{{book.livro.capa.url}}"" >  
                <p class="has-text-weight-semibold">{{book.livro.titulo}}</p>
              </a>
            </div>
        {% endfor %}

    </section>

</div>
</div>
</section>
</section>
{% include "footer.html" %}
  </body>
</html>

templates/header.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
        <title>Skoob!</title>
        <link rel="shortcut icon" type="image/png" href="https://6879kvvc.apps.lair.io/static/imagens/logo.png"/>
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.1/css/bulma.min.css">
		<link rel="stylesheet" href="{% static 'css/bulma-carousel.min.css' %}">
		<link rel="stylesheet" href="{% static 'css/style.css' %}">
    	<script defer src="https://use.fontawesome.com/releases/v5.1.0/js/all.js"></script>
	</head>
	<body>

    	<header class="navbar is-transparent">
    		<div class="container">
    			<div class="navbar-brand">
    		        <a class="navbar-item" href="{% url 'home' %}">
    		            <img src="{% static 'imagens/logo.png' %}" alt="Skoob">
    		        </a>
    			</div>
    			<div id="navbar" class="navbar-menu">
    		        <div class="navbar-end has-text-centered-mobile">
    		            <div class="navbar-item">
    		              <form id="searchform" action="{% url 'books:search' %}" method="post" class="search">{% csrf_token %}
                            <div class="field has-addons">
                              <div class="control">
                                <input class="input is-small" type="text" placeholder="Search.." name="search" required>
                              </div>
                              <div class="control">
                                <button class="button is-small" type="submit"><i class="fa fa-search"></i></button>
                              </div>
                            </div>
                          </form>
    		            </div>
    		            <a class="navbar-item active-link" href="{% url 'home' %}">
    		              Home
    		            </a>
                        {% if user.is_authenticated%}
    		            <div class="navbar-item has-dropdown is-hoverable">
    		                <a class="navbar-link active-link" href="{% url 'home' %}">
    		                  Explore
    		                </a>
    		                <div class="navbar-dropdown is-boxed">
    		                  <a class="navbar-item" href="{% url 'books:myBooks' %}">
    		                    Estante
    		                  </a>
    		                  <a class="navbar-item" href="{% url 'books:reading_books' %}">
    		                    Lendo
    		                  </a>
    		                  <a class="navbar-item" href="{% url 'books:readed_books' %}">
    		                    Lidos
    		                  </a>
                              <a class="navbar-item" href="{% url 'books:read_books' %}">
                                Ler
                              </a>
                              <a class="navbar-item" href="{% url 'users:profile' %}">
                                Perfil
                              </a>
    		                </div>
                        {% endif %}
    		            </div>
    		            <div class="navbar-item">
    		            	{% block content %}
    		            	{% if user.is_authenticated %}
    		            	  <a class="active-link" href="{% url 'logout' %}">Sair</a>
    		            	{% else %}
    		            	  <a class="button is-info is-outlined" href="{% url 'login' %}">Entrar</a>
    		            	{% endif %}
    		            	{% endblock %}
    		            </div>
    		        </div>
    			</div>
    		</div>
    	</header>

		<section class="section banner is-medium">
			<div class='carousel carousel-animated carousel-animate-slide' data-autoplay="true" data-delay="5000">
			  <div class='carousel-container'>
			    <div class='carousel-item has-background is-active'>
			         <a href="{% url 'books:book_info' pk=3 %}">
                  <img class="is-background" id="is-active" src="{% static 'imagens/banner-harry-potter.jpg' %}">
                </a>
			    </div>
			    <div class='carousel-item has-background'>
			         <a href="{% url 'books:book_info' pk=8 %}">
                        <img class="is-background" src="http://2.bp.blogspot.com/-SKy0MzRocrE/TrlK67XM2_I/AAAAAAAADOM/isnxXaczhEY/s1600/ldr-posters-009.jpg" alt="Percy Jackson"/>
                     </a>
			    </div>
			  </div>
			  <div class="carousel-navigation is-overlay">
			      <div class="carousel-nav-left">
			        <i class="fa fa-chevron-left" aria-hidden="true"></i>
			      </div>
			      <div class="carousel-nav-right">
			        <i class="fa fa-chevron-right" aria-hidden="true"></i>
			      </div>
			  </div>
			</div>
			<section class="container conteudo">
				<div class="columns is-desktop has-text-centered">
					<div class="column">
						<div>
							{% block contentSec %}
							{% if user.is_authenticated %}
							  <h2 class="has-text-weight-semibold is-size-4">Olá {{ user.username }}, bem vindo(a) ao Skoob!</h2>
							{% else %}
							  <div class="cont-nolog">
                                    <h2 class="has-text-weight-semibold is-size-4">
                                        Junte-se a comunidade de leitores do Brasil!
                                        <a class="button is-info is-primary" href="{% url 'users:registerUser' %}">Cadastre-se</a>
                                    </h2>
                              </div>
							{% endif %}
							{% endblock %}
						</div>

templates/home.html
{% load staticfiles %}

{% include "header.html" %}

{% if user.is_authenticated %}
<div class="tabs is-centered">
  <ul>
    <li><a href="{% url 'books:myBooks' %}">Estante</a></li>
    <li><a href="{% url 'books:readed_books' %}">Lidos</a></li>
    <li><a href="{% url 'books:read_books' %}">Ler</a></li>
    <li><a href="{% url 'books:reading_books' %}">Lendo</a></li>
  </ul>
</div>
{% endif %}

<section class="livros">
	{% for book in books %}
  <div class=" box-livro">
    <a class="image" href="{% url 'books:book_info' pk=book.pk %}" title="{{book.titulo}}">
      <img src="{{book.capa.url}}" >  
      <p class="has-text-weight-semibold">{{book.titulo}}</p>
    </a>
  </div>
	{% endfor %}
</section>

</div>
</div>
</section>
</section>
{% include "footer.html" %}
</body>
</html>

templates/results.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.1/css/bulma.min.css">
		<link rel="stylesheet" href="{% static 'css/bulma-carousel.min.css' %}">
		<link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script defer src="https://use.fontawesome.com/releases/v5.1.0/js/all.js"></script>

<style>
    .book-info{
        display: inline-block;
        width: 170px;
        margin-left: -40px;
        
    }
	header{
		border-bottom: 3px solid hsl(204, 86%, 53%);
	}
	ul {
		list-style: none;
	}

	li {
		display: inline-block;;
		width: 6.15em;
		height: 9.10em;
		padding: 0;
		margin: 0.625em 1.25em;
		border: solid 0.25em #fff;
		border-radius:  0.3125em;
		-webkit-box-shadow:  0px 0px  0.3125em 0px rgba(0, 0, 0, 0.25);
		box-shadow:  0px 0px  0.3125em 0px rgba(0, 0, 0, 0.25);
	}

	.books-search{
		border-bottom: 0.375em solid #20B2AA;
	    background-color: lightgrey;
	    width: 12.3em;
	    height: 20em;
	}
</style>
</head>
<body>

		<header class="navbar is-transparent">
			<div class="container">
				<div class="navbar-brand">
							<a class="navbar-item" href="{% url 'home' %}">
									<img src="{% static 'imagens/logo.png' %}" alt="Skoob">
							</a>
				</div>
				<div id="navbar" class="navbar-menu">
							<div class="navbar-end has-text-centered-mobile">
									<div class="navbar-item">
										<form id="searchform" action="{% url 'books:search' %}" method="post" class="search">{% csrf_token %}
													<div class="field has-addons">
														<div class="control">
															<input class="input is-small" type="text" placeholder="Search.." name="search" required>
														</div>
														<div class="control">
															<button class="button is-small" type="submit"><i class="fa fa-search"></i></button>
														</div>
													</div>
												</form>
									</div>
									<a class="navbar-item active-link" href="{% url 'home' %}">
										Home
									</a>
											{% if user.is_authenticated%}
									<div class="navbar-item has-dropdown is-hoverable">
											<a class="navbar-link active-link" href="{% url 'home' %}">
												Explore
											</a>
											<div class="navbar-dropdown is-boxed">
												<a class="navbar-item" href="{% url 'books:myBooks' %}">
													Estante
												</a>
												<a class="navbar-item" href="{% url 'books:reading_books' %}">
													Lendo
												</a>
												<a class="navbar-item" href="{% url 'books:readed_books' %}">
													Lidos
												</a>
														<a class="navbar-item" href="{% url 'books:read_books' %}">
															Ler
														</a>
														<a class="navbar-item" href="{% url 'users:profile' %}">
															Perfil
														</a>
											</div>
											{% endif %}
									</div>
									<div class="navbar-item">
										{% block content %}
										{% if user.is_authenticated %}
											<a class="active-link" href="{% url 'logout' %}">Sair</a>
										{% else %}
											<a class="button is-info is-outlined" href="{% url 'login' %}">Entrar</a>
										{% endif %}
										{% endblock %}
									</div>
							</div>
				</div>
			</div>
		</header>
		<section class="container conteudo" style="margin-top:0; border: transparent">
			<div class="columns is-desktop has-text-centered">
				<div class="column">
					<div>
							<div class="">
									<h2 class="has-text-weight-semibold is-size-4">
											{{result1}} <i>"{{query}}"</i>{{result2}}
									</h2>
							</div>

					</div>

					<p><h4>{{result3}}</h4></p>
					<ul class="book-list">
					<br>
					{% for livro in livros %}
					<div class="books-search">
					  <li class="book1"><a href="{% url 'books:book_info' pk=livro.pk %}">
						    <img style="width: 6.15em; height: 8.65em" src="{{livro.capa.url}}" alt="" />
						    </a>
						    <p class="book-info">
						    	<b>Título:</b><br>{{ livro.titulo }}<br><br>
						    	<b>Autor:</b><br> {{ livro.autor}}
						    </p>
						    <h4></h2>
					  </li>
					</div>
					<br>
					{% endfor %}
				</ul>
			</div>
		</section>
{% include "footer.html" %}
</body>
</html>
<!--
Para 'pegar' os demais valores do livro:
genero = {{ livro.genero }}
editora = {{ livro.editora }}
paginas = {{ livro.paginas }}
 -->